# Counter module manifest V2

name: Counter_Task
module_type: counter
enabled: true
debug: false
persist_state: false

# Retry: configure automatic retries for transient failures
retry:
  max_attempts: 3
  backoff_strategy: exponential
  backoff_interval_seconds: 5
  backoff_multiplier: 2
  backoff_max_interval_seconds: 60

# Trigger: execute once per minute
trigger:
  type: schedule
  config:
    type: cron
    # Cron expression: '*/1 * * * *' runs once every minute
    cron_expression: "*/1 * * * *"

# Inputs: describe the data available when the task runs
inputs:
  increment_by:
    description: "Increment to apply during a single run. If omitted, the default from settings is used."
    required: false
    # Note: there is no 'default' here because the value comes from settings

# Settings: define static module configuration
settings:
  # increment_by is a configurable default value
  increment_by: 1
  # Note: 'current_count' was removed because it is managed through context.get_state/update_state
