debug: true
name: S3
module_type: screen_protector
enabled: false
persist_state: false
settings:
  mouse_jiggle_range_min: 1000
  mouse_jiggle_range_max: 5000
trigger:
  type: interval
  config:
    days: 0
    hours: 0
    minutes: 0
    seconds: 5
