# Screen protector module manifest V2

name: ScreenProtector
module_type: screen_protector
enabled: false
debug: false
persist_state: false

# Retry: default transient failure handling
retry:
  max_attempts: 3
  backoff_strategy: exponential
  backoff_interval_seconds: 5
  backoff_multiplier: 2
  backoff_max_interval_seconds: 60

# Trigger: Execute every 5 seconds to check mouse activity frequently
trigger:
  type: schedule
  config:
    type: interval
    seconds: 5

# Inputs: This module does not consume external data.
inputs: {}

# Settings: Configure the mouse movement range
settings:
  mouse_jiggle_range_min: 10
  mouse_jiggle_range_max: 50
